### ISSUE TITLE
UGA workshop request

### ISSUE THREAD

**Issue by wallacelab** [UGA-Carpentries/uga-carpentries.github.io#4]
This Issue is for people from the UGA community to request that we have a Carpentries workshop. This is _not_ a substitute for the official Carpentries workshop request form; it's just to try to organize things centrally here at UGA and prevent duplicated effort.

**Comment by biotemon** [comment]
We are requesting your help to open a UGA Carpentries web page for the upcoming "Programming with R" workshop using the lesson http://swcarpentry.github.io/r-novice-inflammation/ as a reference. The workshop is scheduled for February 7th 2020. 
Thanks,
Instructors: Tito Montenegro and Mike Francis

**Comment by magsol** [comment]
I'm also going to go ahead and make a placeholder request for a website for "Programming with Python", with tentative plans to create a hybrid module consisting of Lessons 1-7 from "Programming with Python" ( https://swcarpentry.github.io/python-novice-gapminder/ ), followed by Lessons 6-9 from "Plotting and Programming in Python" ( https://swcarpentry.github.io/python-novice-gapminder/ ).

I'm also proposing a tentative date for *February 20-21*. I'm currently the only instructor, but would be happy for a second volunteer.

**Comment by wallacelab** [comment]
@biotemon , do we have a location for the Feb 7 workshop? You can probably work with Sandra to reserve one, given your requirements (X people, AV equipment electrical, access preferred). I'd recommend you cap attendance at ~25 people just to keep things manageable.

Edit: Do be aware that Feb 7 is an ILS recruiting day, and Bioinformatics is part of ILS. I honestly don't know how much that will impact things, but figured you should be aware of it.

Edit again: Just checked; Coverdell S175 is full all day, and CAGT 128 (what we used last week) has a class in the morning, so you'll need to look elsewhere.

**Comment by wallacelab** [comment]
@magsol , FYI, I imported a repository (2019-02-20-uga) so you can start adding information on the Feb python workshop as you get it squared away.
